name: "Create YouTube Plus app [More Tweaks] BETA"

on:
  workflow_dispatch:
    inputs:
    
      enable_tweaks:
        description: "Integrate all tweaks"
        type: boolean
        required: true
        default: true

      ipa_url:
        description: "URL to the decrypted IPA file"
        default: ""
        required: true
        type: string

      tweak_version:
        description: "The version of the tweak to use. Enter the version manually from dayanch96/YTLite/releases or leave default"
        default: "5.2b4"
        required: true
        type: string

      display_name:
        description: "App Name (Optional)"
        default: "YouTube"
        required: true
        type: string

      bundle_id:
        description: "BundleID (Optional)"
        default: "com.google.ios.youtube"
        required: true
        type: string
        
      upload_artifact:
        description: "Upload IPA as an artifact (Public)"
        default: true
        required: false
        type: boolean

      catbox_upload:
        description: "Upload IPA to Catbox.moe (URL)"
        default: true
        required: false
        type: boolean
        
      draft_release:
        description: "Create a draft release (Private)"
        default: true
        required: false
        type: boolean


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Main
        uses: actions/checkout@v6.0.1
        with:
          path: main
          submodules: recursive

      - name: Hide sensitive inputs
        uses: levibostian/action-hide-sensitive-inputs@v1
        with:
          exclude_inputs: bundle_id,display_name,info_note,tweak_version

      - name: Download and validate IPA
        run: |
          wget "${{ inputs.ipa_url }}" --no-verbose -O ${{ github.workspace }}/youtube.ipa

          file_type=$(file --mime-type -b ${{ github.workspace }}/youtube.ipa)

          if [[ "$file_type" != "application/x-ios-app" && "$file_type" != "application/zip" ]]; then
            echo "::error::Validation failed: The downloaded file is not a valid IPA. Detected type: $file_type."
            exit 1
          fi

      - name: Install Dependencies
        run: brew install make ldid

      - name: Set PATH environment variable
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH

      - name: Cache Theos
        if: ${{ inputs.enable_tweaks }}
        id: theos
        uses: actions/cache@v5.0.1
        env:
          cache-name: theos_cache_95ab5f4
        with:
          path: theos/
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - name: Setup Theos
        if: ${{ inputs.enable_tweaks && steps.theos.outputs.cache-hit != 'true' }}
        uses: actions/checkout@v6.0.1
        with:
          repository: theos/theos
          ref: 95ab5f4db49cb28ef8fff2d9ec91c840f2ca73f0
          path: ${{ github.workspace }}/theos
          submodules: recursive

      - name: Download iOS SDK
        if: ${{ inputs.enable_tweaks && steps.theos.outputs.cache-hit != 'true' }}
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/xybp888/iOS-SDKs.git
          cd iOS-SDKs
          git sparse-checkout set --no-cone iPhoneOS18.6.sdk
          git checkout
          mv *.sdk $THEOS/sdks
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Install cyan
        run: pipx install --force https://github.com/asdfzxcvbn/pyzule-rw/archive/main.zip

      - name: Download YouTube Plus
        id: download_ytp
        run: |
          deb_url="https://github.com/dayanch96/YTLite/releases/download/v${{ inputs.tweak_version }}/com.dvntm.ytlite_${{ inputs.tweak_version }}_iphoneos-arm.deb"
          wget "$deb_url" --no-verbose -O ${{ github.workspace }}/ytplus.deb

      - name: Clone Open in YouTube (Safari extension)
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/BillyCurtis/OpenYouTubeSafariExtension.git
          cd OpenYouTubeSafariExtension
          git sparse-checkout set --no-cone OpenYouTubeSafariExtension.appex
          git checkout
          mv *.appex ${{ github.workspace }}

      - name: Clone YouTubeHeader
        if: ${{ inputs.enable_tweaks }}
        run: |
          if [ -d "$THEOS/include/YouTubeHeader" ]; then
            echo "YouTubeHeader exists. Pulling latest changes..."
            cd $THEOS/include/YouTubeHeader
            git pull
          else
            echo "YouTubeHeader does not exist. Cloning repository..."
            cd $THEOS/include
            git clone --quiet --depth=1 https://github.com/PoomSmart/YouTubeHeader.git
          fi

          if [ "${{ inputs.enable_demc }}" = "true" ]; then
            echo "Copying YouTubeHeader to YTHeaders..."
            rm -rf "$THEOS/include/YTHeaders"
            cp -r "$THEOS/include/YouTubeHeader" "$THEOS/include/YTHeaders"
          fi
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Clone PSHeader
        if: ${{ inputs.enable_tweaks }}
        run: |
          if [ -d "$THEOS/include/PSHeader" ]; then
            echo "PSHeader exists. Pulling latest changes..."
            cd $THEOS/include/PSHeader
            git pull
          else
            echo "PSHeader does not exist. Cloning repository..."
            cd $THEOS/include
            git clone --quiet --depth=1 https://github.com/PoomSmart/PSHeader.git
          fi
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Clone YouPiP
        if: ${{ inputs.enable_tweaks }}
        run: |
          cd ${{ github.workspace }}
          git clone --quiet --depth=1 https://github.com/PoomSmart/YouPiP.git

      - name: Clone YTUHD
        if: ${{ inputs.enable_tweaks }}
        run: |
          cd ${{ github.workspace }}
          git clone --quiet --depth=1 https://github.com/Tonwalter888/YTUHD.git

          
      - name: Clone Return-YouTube-Dislikes
        if: ${{ inputs.enable_tweaks }}
        run: |
          cd ${{ github.workspace }}
          git clone --quiet --depth=1 https://github.com/PoomSmart/Return-YouTube-Dislikes.git

      - name: Clone YouGroupSettings
        if: ${{ inputs.enable_tweaks }}
        run: |
          cd ${{ github.workspace }}
          git clone --quiet --depth=1 https://github.com/PoomSmart/YouGroupSettings.git

      - name: Clone YouQuality
        if: ${{ inputs.enable_tweaks }}
        run: |
          cd ${{ github.workspace }}
          git clone --quiet --depth=1 https://github.com/PoomSmart/YouQuality.git

      - name: Clone YTVideoOverlay
        if: ${{ inputs.enable_tweaks }}
        run: |
          cd ${{ github.workspace }}
          git clone --quiet --depth=1 https://github.com/PoomSmart/YTVideoOverlay.git

      - name: Clone DontEatMyContent
        if: ${{ inputs.enable_tweaks }}
        run: |
          cd ${{ github.workspace }}
          git clone --quiet --depth=1 --recurse-submodules https://github.com/therealFoxster/DontEatMyContent.git
       
      - name: Clone YTABConfig
        if: ${{ inputs.enable_tweaks }}
        run: |
          cd ${{ github.workspace }}
          git clone --quiet --depth=1 https://github.com/PoomSmart/YTABConfig

      - name: Clone YouMute
        if: ${{ inputs.enable_tweaks }}
        run: |
          cd ${{ github.workspace }}
          git clone --quiet --depth=1 https://github.com/PoomSmart/YouMute

      - name: Clone YTVideoErrorAlert
        if: ${{ inputs.enable_tweaks }}
        run: |
          cd ${{ github.workspace }}
          git clone --quiet --depth=1 https://github.com/PoomSmart/YTVideoErrorAlert

      - name: Clone Gonerino
        if: ${{ inputs.enable_tweaks }}
        run: |
          cd ${{ github.workspace }}
          git clone --quiet --depth=1 https://github.com/castdrian/Gonerino
          
      - name: Build YouPiP
        if: ${{ inputs.enable_tweaks }}
        run: |
          cd ${{ github.workspace }}/YouPiP
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/youpip.deb
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Build YTUHD
        if: ${{ inputs.enable_tweaks }}
        run: |
          cd ${{ github.workspace }}/YTUHD
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/ytuhd.deb
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Build Return-YouTube-Dislikes
        if: ${{ inputs.enable_tweaks }}
        run: |
          cd ${{ github.workspace }}/Return-YouTube-Dislikes
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/ryd.deb
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Build YouGroupSettings
        if: ${{ inputs.enable_tweaks }}
        run: |
          cd ${{ github.workspace }}/YouGroupSettings
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/ygs.deb
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Build YouQuality
        if: ${{ inputs.enable_tweaks }}
        run: |
          cd ${{ github.workspace }}/YouQuality
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/yq.deb
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Build YTVideoOverlay
        if: ${{ inputs.enable_tweaks }}
        run: |
          cd ${{ github.workspace }}/YTVideoOverlay
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/ytvo.deb
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Build DontEatMyContent
        if: ${{ inputs.enable_tweaks }}
        run: |
          cd ${{ github.workspace }}/DontEatMyContent
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/demc.deb
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Build YTABConfig
        if: ${{ inputs.enable_tweaks }}
        run: |
          cd ${{ github.workspace }}/YTABConfig
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/ytab.deb
        env:
          THEOS: ${{ github.workspace }}/theos
          
      - name: Build YouMute
        if: ${{ inputs.enable_tweaks }}
        run: |
          cd ${{ github.workspace }}/YouMute
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/ymute.deb
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Build YTVideoErrorAlert
        if: ${{ inputs.enable_tweaks }}
        run: |
          cd ${{ github.workspace }}/YTVideoErrorAlert
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/ytvea.deb
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Build Gonerino
        if: ${{ inputs.enable_tweaks }}
        run: |
          cd ${{ github.workspace }}/Gonerino
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/gon.deb
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Inject tweaks into IPA
        run: |
          tweaks="ytplus.deb OpenYouTubeSafariExtension.appex"

          for f in *.deb; do
            if [ -f "$f" ]; then
              tweaks="$tweaks $f"
            fi
          done
          
          cyan -i youtube.ipa -o YouTubePlus_${{ env.YT_VERSION }}_v${{ inputs.tweak_version }}.ipa -uwef $tweaks -n "${{ inputs.display_name }}" -b ${{ inputs.bundle_id }}
      
      - name: Upload IPA to Catbox
        if: ${{ inputs.catbox_upload }}
        run: |
          RESPONSE=$(curl -F "reqtype=fileupload" -F "fileToUpload=@YouTubePlus_${{ env.YT_VERSION }}_v${{ inputs.tweak_version }}.ipa" https://catbox.moe/user/api.php)
          CATBOX_URL=$(echo $RESPONSE | grep -o -E 'https://files.catbox.moe/[^"]*')
          echo "Uploaded the IPA to $CATBOX_URL"
          CATBOX_FILE=$(echo $CATBOX_URL | sed 's|https://files.catbox.moe/||')
          echo "CATBOX_FILE=$CATBOX_FILE" >> $GITHUB_ENV
          echo "CATBOX_URL=$CATBOX_URL" >> $GITHUB_ENV
      - name: Upload IPA as an Artifact
        if: ${{ inputs.upload_artifact }}
        uses: actions/upload-artifact@v6
        with:
          name: YouTubePlus ${{ env.YT_VERSION }} v${{ inputs.tweak_version }}
          path: YouTubePlus_${{ env.YT_VERSION }}_v${{ inputs.tweak_version }}.ipa
          
      - name: Create a Draft Release
        if: ${{ inputs.draft_release }}
        uses: softprops/action-gh-release@v2.5.0
        with:
          tag_name: ytp-${{ github.run_number }}
          name: YouTubePlus ${{ env.YT_VERSION }} v${{ inputs.tweak_version }} (${{ github.run_number }}) 
          files: YouTubePlus_${{ env.YT_VERSION }}_v${{ inputs.tweak_version }}.ipa         
          draft: true

      - name: Job Summary - Build Complete
        run: |
          echo -e '### ðŸ› ï¸ Create YouTube Plus app Complete!' >> $GITHUB_STEP_SUMMARY
      - name: Job Summary - Output the Artifact Upload
        if: ${{ inputs.upload_artifact }}
        run: |
          echo -e '### ðŸ“¦ Artifact Upload\n\nUpload IPA as an artifact successfully! Refresh and [Scroll down](#artifacts) to view the artifact. Note that you must be signed in to GitHub to download it.' >> $GITHUB_STEP_SUMMARY
      - name: Job Summary - Output the IPA URL (Catbox Upload)
        if: ${{ inputs.catbox_upload }}
        run: |
          echo -e '### ðŸ± Catbox Upload\n\nUpload IPA to Catbox successfully! Here is a permanent shareable link: '$CATBOX_URL >> $GITHUB_STEP_SUMMARY
      - name: Job Summary - Output a Draft Release Link
        if: ${{ inputs.draft_release }}
        run: |
          echo -e '### ðŸš€ Draft Release\n\nDraft release has been created successfully! You can view your release here: https://github.com/${{ github.repository }}/releases' >> $GITHUB_STEP_SUMMARY
     
      - name: Job Summary - Cleanup
        run: |
          echo -e '### ðŸ§¹ Cleanup\n\nYou can remove previous GitHub Actions run here: https://github.com/${{ github.repository }}/actions/workflows/delete-old-workflows-run.yml And if you want to delelte old draft releases you have then here: https://github.com/${{ github.repository }}/actions/workflows/delete-old-draft-releases.yml' >> $GITHUB_STEP_SUMMARY
